name: project
description: "A new Flutter project."
publish_to: 'none' # Remova esta linha se você desejar publicar no pub.dev

# As seguintes linhas definem a versão e o número de compilação para sua aplicação.
# Um número de versão é composto por três números separados por pontos, como 1.2.43
# seguido por um número de compilação opcional separado por um +.
# Tanto o número da versão quanto o número da compilação podem ser substituídos na construção do Flutter
# especificando --build-name e --build-number, respectivamente.
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # A linha abaixo adiciona a fonte de ícones Cupertino à sua aplicação.
  # Use com a classe CupertinoIcons para ícones de estilo iOS.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # O pacote "flutter_lints" abaixo contém um conjunto de lints recomendados para
  # incentivar boas práticas de codificação. O conjunto de lints fornecido pelo pacote é
  # ativado no arquivo `analysis_options.yaml` localizado na raiz do seu
  # pacote. Consulte esse arquivo para informações sobre como desativar regras de lint específicas
  # e ativar outras adicionais.
  flutter_lints: ^4.0.0

flutter:
  # A linha abaixo garante que a fonte de ícones Material seja
  # incluída na sua aplicação, para que você possa usar os ícones na
  # classe Material Icons.
  uses-material-design: true

  # Para adicionar ativos à sua aplicação, adicione uma seção de ativos, como esta:
  assets:
    - assets/images/
    - assets/svg/
    # - images/a_dot_ham.jpeg

  # Um ativo de imagem pode referir-se a uma ou mais "variantes" específicas de resolução,
  # veja https://flutter.dev/to/resolution-aware-images

  # Para adicionar fontes personalizadas à sua aplicação, adicione uma seção de fontes aqui,
  # nesta seção "flutter". Cada entrada nesta lista deve ter uma
  # chave "family" com o nome da família da fonte, e uma chave "fonts" com uma
  # lista que fornece o ativo e outros descritores para a fonte. Por exemplo:
  fonts:
    - family: Baloo_Thambi_2
      fonts:
        - asset: fonts/BalooThambi2-VariableFont_wght.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
